### ISSUE TITLE
It works? I met permission denied

### ISSUE THREAD

**Issue by bluebad** [h0tbird/docker-pppd#1]
Sorry, I spent a whole day on it, not works.
Error info screen shot below:
![20160526180141](https://cloud.githubusercontent.com/assets/18501400/15571173/f79b279c-236b-11e6-9df0-5fbe8df22c9e.jpg)

**Comment by h0tbird** [comment]
I don't use nor maintain it anymore. I don't recommend anyone to use it in its current state.
Sorry mate!

**Comment by bluebad** [comment]
Why? I think people need it. Is it has any issues?

**Comment by h0tbird** [comment]
Sure it has issues. I initially planned to use it in `CoreOS` systems but then I changed my mind and I abandoned the idea. Feel free to fork and re-use the code but I won't invest time on it because I have no interest and I am working on other things right now.

**Comment by h0tbird** [comment]
@bluebad: I decided to remove it completely because it is useless to anyone.
